### PR TITLE
bug(runtime): functions can be registered twice

### LINKED ISSUE #300: bug(runtime): handle scenario where two functions are registered as one
When registering functions in segment files a small typo is made easily, especially when using `version`, or when functions are registered with different names using `as`. Jitar doesn't notify the developer that a typo has been made.

The following configurations should not be allowed.

```json
{
    "./shared/sayHello":
    {
        "sayHello": { "access": "public", "version": "1.0.0" }
    },
     "./shared/sayHelloV2":
    {
        "sayHello": { "access": "public", "version": "1.0.0" }
    }
}
```

```json
{
    "./database": {
        "getOrganisation": {
            "as": "getEmployee"
            "access": "public"
        },
        "getEmployee": {
            "as": "getEmployee"
            "access": "public"
        }
    }
}
```

In both cases the first function in the configuration is registered and available as RPC call. The second function is not available.

The expectation would be that this segment configuration is not correct and should throw an error.

### PR DESCRIPTION
**Pull request by BasMasking**
Fixes #300

Changes proposed in this pull request:
- added segment cache validation

@MaskingTechnology/jitar

### CODE REVIEW

File: packages/caching/src/building/SegmentCacheBuilder.ts [hunk 1]
```diff
@@ -68,11 +71,36 @@ export default class SegmentCacheBuilder
...
+        {
+            this.#checkForDuplicateImplementations(procedure);
+        }
+    }
+
+    #checkForDuplicateImplementations(procedure: SegmentProcedure): void
+    {
+        for (const implementation of procedure.implementations)
+        {
+            const duplidate = procedure.implementations.find(other =>
```
Comment (petermasking) [inline packages/caching/src/building/SegmentCacheBuilder.ts:94]: duplidate?

**Review by petermasking — CHANGES_REQUESTED** [review]

**Review by petermasking — APPROVED** [review]
