### PR TITLE
fix(reflection): Fails on minified scripts

### LINKED ISSUE #166: Reflection fails on minified scripts
After minifying a script it fails with the message that it had an unexpected token ',' (comma).

### PR DESCRIPTION
**Pull request by petermasking**
Fixes #166 

Changes proposed in this pull request:
- fixed operator separation when multiple operators are placed behind each other
- added support for regex, not expressions and multiple declarations
- added generator support for classes
- added 'known limitations' section to the readme
- migrated to vitest

@MaskingTechnology/jitar

### CODE REVIEW

File: packages/jitar-reflection/src/parser/Parser.ts [hunk 1]
```diff
@@ -207,7 +207,12 @@ export default class Parser
...
         }
-        else if (token.hasValue(Divider.TERMINATOR))
+        else if (token.hasValue(Operator.DIVIDE) || token.hasValue(Operator.NOT))
+        {
+            // Regular expression or logical not
+            return this.#parseExpression(tokenList);
+        }
+        else if (token.hasValue(Divider.TERMINATOR) || token.hasValue(Divider.SEPARATOR))
         {
             tokenList.step(); // Read away the terminator
```
Comment (BasMasking) [inline packages/jitar-reflection/src/parser/Parser.ts:217]: It reads the terminator or the separator

**Review by BasMasking — CHANGES_REQUESTED** [review]

**Review by BasMasking — APPROVED** [review]
