### PR TITLE
116 extends exceptions to status codes mappings

### LINKED ISSUE #116: Extends exceptions to status codes mappings
We have mappings for not found exceptions and bad request exceptions. We need to extend the number of exceptions to support a wider range of status codes.

The most used exceptions that will be added are:

- Unauthorized (401)
- Payment required (402)
- Forbidden (403)
- I'm a teapot (418)
- Not implemented (501)

### PR DESCRIPTION
**Pull request by petermasking**
Fixes #116 

Changes proposed in this pull request:
- added generic errors
- refactored existing error to a generic type
- translated generic error to their status code

@MaskingTechnology/jitar

### CODE REVIEW

File: packages/jitar-nodejs-server/src/controllers/RPCController.ts [hunk 1]
```diff
@@ -174,15 +172,13 @@ export default class RPCController
...
-        if (INVALID_REQUEST_ERRORS.some(invalidError => error instanceof invalidError))
-        {
-            return 400;
-        }
-
-        if (NOT_FOUND_ERRORS.some(notFoundError => error instanceof notFoundError))
-        {
-            return 404;
-        }
+        if (error instanceof BadRequest)    return 400;
```
Comment (BasMasking) [inline packages/jitar-nodejs-server/src/controllers/RPCController.ts:175]: The alignment is off for the BadRequest check

**Review by BasMasking — CHANGES_REQUESTED** [review]
One alignment issue found
