### PR TITLE
fix(runtime): fixed incorrect parsing of return values

### LINKED ISSUE #451: Proper content type for return values
When an application is deployed in a cluster, the result of procedures are sent back and forth using the http protocol. We don't have the possibility to detect whether the value in the body is a boolean value. The current content-type is set to text/plain and the value to `true` or `false`.

We don't want to assume that any `true` or `false` values in the body are by definition booleans. So we would like to add a content type header so we can detect whether the value should be interpreted as a boolean or a string. The same issue occurs for numbers.

This issue is found in the `access-protection` example, so this can be used for testing.

### PR DESCRIPTION
**Pull request by BasMasking**
Fixes #451

Changes proposed in this pull request:
- Introduced own content-types to indicate the return type (boolean / number)
- Set the return type based on the content
- Parse return value based on content type header

@MaskingTechnology/jitar

### CODE REVIEW

File: examples/concepts/access-protection/src/web/guessSecret.ts [hunk 1]
```diff
@@ -3,7 +3,9 @@ import checkSecret from '../game/checkSecret';
 
 export default async function guessSecret(secret: string): Promise<string>
```
Comment (petermasking) [inline examples/concepts/access-protection/src/web/guessSecret.ts:4]:
```suggestion
export default async function guessSecret(secret: number): Promise<string>
```

Is this a good idea? It feels more logical to me. The only consequence is that we have to change the requests from GET to POST so we can provide the correct content type.

File: packages/runtime/test/services/Remote.spec.ts [hunk 2]
```diff
@@ -0,0 +1,47 @@
+
+import { describe, expect, it } from 'vitest';
+
+import Remote from '../../src/services/Remote';
+
+import { REQUESTS } from '../_fixtures/services/Remote.fixture';
+
+const remote = new Remote('http://localhost:3000');
```
Comment (petermasking) [inline packages/runtime/test/services/Remote.spec.ts:8]: Should we create the remote in the fixture?

**Review by petermasking — CHANGES_REQUESTED** [review]

**Review by petermasking — APPROVED** [review]
